add : all aldi sayuti view classes.
JavkhlanK/Sketchware-Pro pull request #34
Opened 2021-04-13 13:41 UTC by MarkDroid

2021-04-13 13:47 UTC, JavkhlanK requested changes
Please rename the fields back to their original names.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemBottomNavigationView.java
> +    public ViewBean f12a;
You used JaDX to decompile the files. And it automatically renamed a field. This will not work, unless you edit all references to that field.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemCodeView.java
> +    public ViewBean f13a;
Same thing here, this field has a different name now. Rename it to its original name, please.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemGoogleSignInButton.java
> +    public ViewBean f14a;
Here, again a renamed field.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemLottieAnimation.java
> +    public ViewBean f15a;
This field has also been renamed, please revert it.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemOTPView.java
> +    public ViewBean f16a;
Renamed.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemPatternLockView.java
> +    public ViewBean f17a;
Also renamed.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemRecyclerView.java
> +    public ViewBean f18a;
Renamed too. Revert its name to `a`.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemTabLayout.java
> +    public ViewBean f19a;
This field has also been renamed by JaDX.

2021-04-13 13:47 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/editor/view/item/ItemYoutubePlayer.java
> +    public ViewBean f20a;
Renamed, please revert its name to `a`.

2021-04-13 13:55 UTC, MarkDroid commented
bru, aldi name them like that so jadx get the original name and put it for example :
you create a private ViewBean vb
fernflower rename ViewBean var1, jadx keep it same as vb
try yourself decompile one of those classes youll find that really that exist
+
the renamed from a comment is belong to a.a.a and exactly a.a.a.sy means all fields are correct and i didnt rename any one of them

2021-04-13 13:58 UTC, JavkhlanK commented
Well those variables can't have different ones, as they are *fields* of that class. These names **do** get saved to the DEX file, they are case sensitive, and aren't simple registers, unlike local variables/fields.

2021-04-13 14:00 UTC, MarkDroid commented
check the files and see that they are working, they are the same classes that i used to make new widgets.

2021-04-13 17:52 UTC, AlucardTN commented
merge the pull or dumb

2021-04-14 17:38 UTC, JavkhlanK commented
Alright I reviewed those files, and didn't find any DEX code referencing them (except in the files itself). That means it's safe to change (at least) field `a`.

2021-04-14 17:39 UTC, merged