feat, fix, style : see commits.
JavkhlanK/Sketchware-Pro pull request #77
Opened 2021-04-19 23:19 UTC by AlucardTN

2021-04-19 23:19 UTC, AlucardTN commented
DesignActivity is high file even i used CRLF and design want to detect new lines or changes, btw i only changed things of compile from line proguard

2021-04-19 23:19 UTC, AlucardTN commented
also, hosni forget to rename hes methods, so i fixed them

2021-04-19 23:20 UTC, AlucardTN commented
thats all, still some bugs about incremental build

2021-04-20 04:25 UTC, JavkhlanK commented
Are the files you committed with LF separators or CRLF ones? I can't quite tell on `R8Executor`

2021-04-20 10:24 UTC, AlucardTN commented
i used LF (\n)

On Tue, Apr 20, 2021, 05:25 Javkhlan K. ***@***.***> wrote:

> Are the files you committed with LF separators or CRLF ones? I can't quite
> tell on R8Executor
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JavkhlanK/Sketchware-Pro/pull/77#issuecomment-822963940>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARSWCSH5AAWFRTJ3XDTNT6LTJT63VANCNFSM43G5J3PQ>
> .
>

2021-04-20 19:14 UTC, JavkhlanK requested changes

2021-04-20 19:36 UTC, AlucardTN commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
i the first one, i mean DEX not FEX, and i the second one, this import is with a fault, you can remove it

2021-04-20 19:38 UTC, JavkhlanK commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
Could you fix these yourself and test changes out again? I don't want to edit your changes right now from the web without testing them...

2021-04-20 19:40 UTC, AlucardTN commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
Am I lying to you when i say " i have tested, also Ilyasse & Tyron tested it.

2021-04-20 19:42 UTC, AlucardTN commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
edit them from the web directly, I'll after 1 hours send git the repo again and send you what working and what's not working later

2021-04-20 19:42 UTC, JavkhlanK commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
what if some file was referencing the constant in `BuildSettings` with the wrong name and I missed it, I meant you should rename it to `DEX_...` and see if it still compiles

2021-04-20 19:44 UTC, AlucardTN commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
only `DesignActivity` and `BuildSettingsDialog` reference to that, just edit from web directly.

2021-04-20 19:46 UTC, JavkhlanK commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
hmmm okay

2021-04-20 19:47 UTC, JavkhlanK commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
please try to fix changes people request yourself next time

2021-04-20 19:49 UTC, AlucardTN commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
wdym

2021-04-20 19:53 UTC, JavkhlanK commented on app/src/main/java/mod/hey/studios/build/BuildSettings.java
> +import com.android.tools.r8.w.S;
like why do i have to edit a PR by you

2021-04-20 20:29 UTC, closed without merging